### ISSUE TITLE
add timestamps for rendering of time-lapse data

### ISSUE THREAD

**Issue by BinYangOptics** [napari/napari-animation#44]
It would be great that if there is an option to add timestamps for rendering of time-lapse data.
Thanks.

**Comment by alisterburt** [comment]
Thanks for the suggestion @BinYangOptics !

My feeling is that that this is a little bit out of scope for napari-animation and is more about napari itself - there is some text support shown in [this example](https://napari.org/tutorials/applications/annotate_segmentation.html) and a bit more detail about how text works in the original `TextManager` PR napari/napari#1374

Does this solve your issue properly?

**Comment by BinYangOptics** [comment]
Thanks for your suggestion @alisterburt. I am not sure how to use the `TextManager` to add Text for the time stamp. But I was able to export the rendered frames in PNG, add text to the PNGs using OpenCV, and then create a movie using ffmpeg.

**Comment by alisterburt** [comment]
awesome - glad you got sorted!

**Comment by sofroniewn** [comment]
I could imagine napari-animation adding a frame number, but that doesn't seem so useful. A timestamp is something we should add to napari. It can definitely be done with the `TextManager`, but we could definitely make that easier for users. I'm going to close this issue here, but might make a new one on napari and reference this.
